### ISSUE TITLE
repeat

### ISSUE THREAD

**Issue by cdshaffer** [cdshaffer/starterator#14]
When doing whole phage of redi, starterator crashed. Was logging everything at the time.  Starterator was working on pham 3635 which was for redi_64 according to log
`

ERROR: Empty sequences found: Redi_69

 CLUSTAL 2.1 Multiple Sequence Alignments

Sequence format is Pearson
exception in starterator
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/seastudent/PycharmProjects/starterator/starterator/uiStarterate.py", line 297, in run
    self.starterate()
  File "/home/seastudent/PycharmProjects/starterator/starterator/uiStarterate.py", line 302, in starterate
    gui=self, event=self.stop_thread)
  File "/home/seastudent/PycharmProjects/starterator/starterator/starterate.py", line 112, in starterate
    final_file, short_final = phage.final_report()
  File "/home/seastudent/PycharmProjects/starterator/starterator/report.py", line 52, in final_report
    self.make_reports()
  File "/home/seastudent/PycharmProjects/starterator/starterator/report.py", line 77, in make_reports
    pham = gene_report.make_report(whole=True)
  File "/home/seastudent/PycharmProjects/starterator/starterator/report.py", line 267, in make_report
    self.pham.align()
  File "/home/seastudent/PycharmProjects/starterator/starterator/phams.py", line 133, in align
    self.call_clustal(file_name+".fasta")
  File "/home/seastudent/PycharmProjects/starterator/starterator/phams.py", line 107, in call_clustal
    '-quicktree'])
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['clustalw', '-infile=/home/seastudent/.starterator/Intermediate Files/Pham3635.fasta', '-quicktree']' returned non-zero exit status 255`

**Comment by cdshaffer** [comment]
this is a repost of same issue
