### ISSUE TITLE
starterator crash with empty sequence

### ISSUE THREAD

**Issue by cdshaffer** [cdshaffer/starterator#15]
When doing whole phage of *Redi*, starterator crashed. Was logging everything at the time.  Starterator was working on pham 3635 which was for redi_64 according to log

```
ERROR: Empty sequences found: Redi_69

 CLUSTAL 2.1 Multiple Sequence Alignments
Exception in thread Thread-6:
Traceback (most recent call last):
  File "starterator/uiStarterate.py", line 297, in run: self.starterate()
  File "/starterator/uiStarterate.py", line 302, in starterate: gui=self, event=self.stop_thread)
  File "starterator/starterate.py", line 112, in starterate: final_file, short_final = phage.final_report()
  File "starterator/report.py", line 52, in final_report: self.make_reports()
  File "starterator/report.py", line 77, in make_reports: pham = gene_report.make_report(whole=True)
  File "starterator/report.py", line 267, in make_report:    self.pham.align()
  File "starterator/phams.py", line 133, in align:    self.call_clustal(file_name+".fasta")
  File "starterator/phams.py", line 107, in call_clustal:    '-quicktree'])
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['clustalw', '-infile=/home/seastudent/.starterator/Intermediate Files/Pham3635.fasta', '-quicktree']' returned non-zero exit status 255
```

I checked phamerator database, the translation is there in the database. Curiously this is the very last gene in the phage.

**Comment by cdshaffer** [comment]
put a breakpoint in with condition for self.pham_no == 3635; the fasta file in the folder is indeed missing the fasta sequence for redi_69. Also looking at the varibales, there is no sequence for {Pham} self.genes["Redi_69"].sequence.seq so it looks like the construction of the seqRecord failed somehow.

**Comment by cdshaffer** [comment]
ok, checking it looks like the issue is that there are no upstream stop codons between the start codon for the last gene and the end of the phage. So error here is likely again in the routine for "find_upstream_start_site()"

**Comment by cdshaffer** [comment]
checked redi does not crash cdshaffer/PECAAN_text branch.

**Comment by cdshaffer** [comment]
checked redi on v1.1.0-beta does not crash. probably solved by code updates for other phage
